### ISSUE TITLE
URL being escaped when getting design documents with authentication

### ISSUE THREAD

**Issue by davidedwardjohnson** [danielwertheim/mycouch#75] opened 2015-04-20 10:37 UTC
Hi there,

I have run into an issue when attempting to get a design document for a database when authentication is enabled.
When trying to GET a design document with the Id "_design/users" then UrlSegment escapes the URL and the eventual request gets sent to 

*databasename*/_design%2Fusers

The response from CouchDB is a 301 to the actual URL /*databasename*/_design/users which the HttpClient automatically redirects to.  I can see this using Fiddler.
The problem arises here because the default behaviour of HttpClient appears to not include any authentication information in the redirect as explained on MSDN.

https://msdn.microsoft.com/en-us/library/system.net.httpwebrequest.allowautoredirect%28v=vs.110%29.aspx

This means that against a database with authentication turned on these requests will always fail.

This issue does not happen when using Cloudant as it appears that it can accept URLs that have been escaped without having to do a redirect.

David

**Comment by SrGrieves** [comment] 2015-04-21 14:30
I came here to report the exact same issue.

**Comment by danielwertheim** [comment] 2015-04-21 17:04
Provide some code and details on how to repro. Just getting `_design/users` using `Client.Documents.GetAsync` seems to work fine for me against a custom install of CouchDB.

**Comment by danielwertheim** [comment] 2015-04-21 17:14
Never mind. Found it.

**Comment by danielwertheim** [comment] 2015-04-21 17:40
Getting a "normal" document with e.g. `id=person/1` needs the encode to `person2%F1` while design docs seem to work fine with `_design/foo` when authentication is on due to the redirect.

Not sure how to handle this client side, could do non encode if against `_design`

**Comment by SrGrieves** [comment] 2015-04-21 20:14
That would solve my issue.  It's really just that specific case that's a problem.

**Comment by davidedwardjohnson** [comment] 2015-04-21 20:50
I guess that skipping the encode if it is a design document is a solution that may be worth implementing now.  It could be worth following that up by looking into manually handling the redirect on the HttpClient so that authentication is re-applied?  If there is any chance that Couch could return a redirect code for any reason then it would then be handled.

**Comment by danielwertheim** [comment] 2015-04-24 17:48
Fix is in develop. Sorry for the delay. This makes it the correct way I hope. Were I take control of the redirect and don't double encode.

**Comment by willholley** [comment] 2015-04-24 19:09
interestingly, https://github.com/apache/couchdb-chttpd/blob/ab80f3131e244af967e2d162925ee45008d54a50/src/chttpd_db.erl#L512 suggests CouchDB 2.0 and Cloudant handle this through the clustered interface without a redirect (would be good to confirm with a test / curl reproduction). If so, it's probably worth registering a ticket with CouchDB to get the same behaviour in the non-clustered interface..

**Comment by danielwertheim** [comment] 2015-04-24 23:06
@davidedwardjohnson @SrGrieves New Nuget v3.1.1 should fix this

@willholley I guess you will register a ticket for it

**Closed by danielwertheim** 2015-04-24 23:06 UTC
Labels: bug, investigate

**Comment by willholley** [comment] 2015-04-26 18:35
CouchDB ticket at https://issues.apache.org/jira/browse/COUCHDB-2674

**Comment by SrGrieves** [comment] 2015-05-20 17:25
@danielwertheim Thank you.  Works perfectly (using v.3.2.0).
