### ISSUE TITLE
Could not load file or assembly EnsureThat

### ISSUE THREAD

**Issue by opiethehokie** [danielwertheim/mycouch#86] opened 2015-07-22 13:09 UTC
I've been using the NuGet package for this project (version 3.2.0) in an ASP.NET 5 app and it worked great on the beta3 and beta4 releases, now moving to the beta5 release I see this error:

\>dnx . kestrel
System.IO.FileNotFoundException: Could not load file or assembly 'EnsureThat, Version=2.0.0.39118, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'EnsureThat, Version=2.0.0.39118, Culture=neutral, PublicKeyToken=null'
   at MyCouch.MyCouchUriBuilder..ctor(String serverUri)

"dnu restore" succeeds and even a "dnu build" is successful, I'm not sure what's different when I actually try to run the app. I only see EnsureThat 2.0.0.0 in NuGet though.

**Comment by JanSichula** [comment] 2015-07-29 06:52
Hello Michael,

I am experiencing exactly the same behavior at my development machine. I have a bad feeling that that there might be some regression in DNX Beta 5. With Beta 6 it is even worse – it does not even resolve the EnsureThat assembly during build time. 

P. S. Am I on the right track in supposing that you need to resolve this in order to update bits at Bluemix build-pack to a newer version than Beta 3?

**Comment by opiethehokie** [comment] 2015-07-29 16:12
@JanSichula yes I am working on updating the Bluemix buildpack. Beta 4 will work but not beta 5.

Trying to dig into it more, but enabling logging doesn't seem to provide much info:
=== Pre-bind state information ===
LOG: DisplayName = EnsureThat, Version=2.0.0.39118, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = .dnx/runtimes/dnx-clr-win-x86.1.0.0-beta5/bin/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file: .dnx\runtimes\dnx-clr-win-x86.1.0.0-beta5\bin\dnx.clr.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL .dnx/runtimes/dnx-clr-win-x86.1.0.0-beta5/bin/EnsureThat.
DLL.
LOG: Attempting download of new URL .dnx/runtimes/dnx-clr-win-x86.1.0.0-beta5/bin/EnsureThat/
EnsureThat.DLL.
LOG: Attempting download of new URL .dnx/runtimes/dnx-clr-win-x86.1.0.0-beta5/bin/EnsureThat.
EXE.
LOG: Attempting download of new URL .dnx/runtimes/dnx-clr-win-x86.1.0.0-beta5/bin/EnsureThat/
EnsureThat.EXE.

**Comment by JanSichula** [comment] 2015-08-05 08:51
Hello Michael,

I appreciate your effort and I understand that ASP.NET support at Bluemix is presently at experimental stage. My hopes were to use it for a production use but it is clearly too early. Hopefully it will get stable later during year.

**Comment by danielwertheim** [comment] 2015-08-13 20:06
Ensure that is currently being updated to support 4.6 and asp.net 5 core super duper confusing framework stuff as documented here https://github.com/danielwertheim/Ensure.That/issues/16

**Comment by danielwertheim** [comment] 2015-08-22 07:19
Ensure.That is updated to support vNext stuff. Work has begun with MyCouch. Activity can be followed in this branch: https://github.com/danielwertheim/mycouch/tree/feature/vnext

Closing as work for this will be covered by #87

**Closed by danielwertheim** 2015-08-22 07:19 UTC
